### PR TITLE
pinning latest aiohttp and guillotina versions

### LINKED ISSUE #1: Upgrade to g 4
setup.py should also be adapted right?

To something like
```
    install_requires=[
        'setuptools',
        'guillotina>=4.0.0,<5.0.0',
        'aiohttp<4.0.0',
        'boto3',
        ...
    ],
```

### PR DESCRIPTION
**Pull request by lferran**
closes https://github.com/guillotinaweb/guillotina_s3storage/issues/1

### CODE REVIEW

**Comment by bloodbare** [comment]
@lferran  can you add .travis to run the tests ?

**Comment by vangheem** [comment]
Unfortunately, the tests require an s3 bucket to run against I think.

**Comment by bloodbare** [comment]
@vangheem isn't there any public bucket for testing ?

**Comment by vangheem** [comment]
Not that I'm aware of.

**Comment by bloodbare** [comment]
@lferran if you feel strong to write down a testing layer to have S3 dummy server like https://github.com/adobe/S3Mock great! Are you strong enough?

**Comment by bloodbare** [comment]
also https://github.com/findify/s3mock

**Comment by lferran** [comment]
yup I'll give a try! :muscle: :sweat_smile:

**Comment by lferran** [comment]
What about serializing the requests/responses, and then replaying them when the url matches? kind of a simpler custom vcrpy-like solution?

**Comment by vangheem** [comment]
@lferran fine with me--just a different type of mock!

**Comment by bloodbare** [comment]
@lferran fine with me too

**Comment by lferran** [comment]
I'm having a lot of problems with the TUS-related tests..

I don't understand why you `tus_patch()` each chunk individually instead of patching the whole file and then letting the implementation deal with the chunk post requests.

**Comment by vangheem** [comment]
I imagine the intention was to simulate using tus for uploading chunks at a time.

Is it more difficult to mock?

**Comment by lferran** [comment]
It's very weird. We are observing the following bug:

On `test_iterate_storage`, from the 2nd iteration of the loop, `mng.upload()` fails due to `self._pointer` of `FakeContentReader` having the value of the last loop ran. Therefore, the upload manager fails [here](https://github.com/plone/guillotina/blob/master/guillotina/files/manager.py#L259)

**Comment by lferran** [comment]
@dmanchon found out that the problem was due to reusing the same request

**Comment by vangheem** [comment]
Travis activated now as well.

**Comment by vangheem** [comment]
does travis run on PRs from a fork?

**Comment by dmanchon** [comment]
@lferran  i propose to change (or create a new) fixture with the content property patched:
```
class PatchedBaseRequest(aiohttp.web_request.Request):
    @property
    def content(self):
        return self._payload

@pytest.fixture(scope='function')
def own_dummy_request(dummy_request, aiohttp_mocks):
    dummy_request.__class__ = PatchedBaseRequest
    yield dummy_request
```

This will allow reusing the 'reified' method `content` and also didnt force us to change the test itself.

**Comment by bloodbare** [comment]
@lferran can you move your branch to the repo so travis detects and runs the tests ?

**Pull request closed without merging**
